name: Tests MacOSX

on:
  push:
  pull_request:
    
jobs:
  # build_virus_macrophage:

  #   runs-on: macos-11

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Install dependencies
  #     run : brew install gcc@10

  #   - name: Build Virus Macrophage project
  #     run: |
  #       make virus-macrophage-sample
  #       make PHYSICELL_CPP=g++-10
        
  #   - name: Run Virus Macrophage cell lines project
  #     run: |
  #       ./virus-sample


  # build_physiboss_cell_lines:

  #   runs-on: macos-11

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Install dependencies
  #     run : brew install gcc@11
      
  #   - name: Build PhysiBoSS cell lines project
  #     run: |
  #       make physiboss-cell-lines-sample
  #       make clean
  #       make PHYSICELL_CPP=g++-11
        
  #   - name: Run PhysiBoSS cell lines project
  #     run: |
  #       ./PhysiBoSS_Cell_Lines
  
  # build_physimess:

  #   runs-on: macos-11

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Install dependencies
  #     run : brew install gcc@11
      
  #   - name: Build PhysiMeSS project
  #     run: |
  #       make physimess-sample
  #       make clean
  #       make PHYSICELL_CPP=g++-11
        
  #   - name: Run PhysiMeSS project
  #     run: |
  #       ./project
  #       ./project config/Fibre_Initialisation/mymodel_initialisation.xml
  #       ./project config/Cell_Fibre_Mechanics/mymodel_rotating.xml

  test_arg_parse:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run : brew install gcc@11

    - name: Build ArgParse project
      run: |
        make template
        make clean
        make -j 12 PHYSICELL_CPP=g++-11      

    - name: Run ArgParse project no arguments
      run: |
        ./project

    - name: Run ArgParse project with unflagged config file
      run: |
        ./project ./config/PhysiCell_settings.xml

    - name: Run ArgParse project with flagged config file
      run: |
        ./project -c ./config/PhysiCell_settings.xml

    - name: Run ArgParse project with flagged output directory
      run: |
        ./project -o output/test/the/arg/parser

    - name: Run ArgParse project with unflagged config file and output directory
      run: |
        ./project ./config/PhysiCell_settings.xml -o output/test/the/arg/parser

    - name: Run ArgParse project with flagged config file and output directory
      run: |
        ./project -c ./config/PhysiCell_settings.xml -o output/test/the/arg/parser
